/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Create a document");
gchar *s = N_("Select type");
gchar *s = N_("Please, select the type of document to create.\n"
              "You can choose a short name, do not confuse it with the file name.");
gchar *s = N_("Description :");
gchar *s = N_("Short name : ");
gchar *s = N_("Select source document");
gchar *s = N_("This document read document from one or more other document. Please, choose these documents.");
gchar *s = N_("Available documents");
gchar *s = N_("Connect to");
gchar *s = N_("Add ->");
gchar *s = N_("<- Remove");
gchar *s = N_("Add all ->");
gchar *s = N_("<- Remove all");
gchar *s = N_("Create views");
gchar *s = N_("You can create one or more views for this document. Note that you have to create at least one view.");
gchar *s = N_("Available views");
gchar *s = N_("Create views");
gchar *s = N_("Add ->");
gchar *s = N_("<- Remove");
gchar *s = N_("Add all ->");
gchar *s = N_("<- Remove all");
