/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Create a new view");
gchar *s = N_("Please, select the type of view you want to create.");
