
<html>
<head>
<title>Verbose Journal - GTT</title>
</head>
<body>
<center>
<h1>Verbose Journal for <?gtt $project_title ?> - <?gtt $project_desc ?></h1>

This is the verbose journal, showing all data:
(handy for debugging and what not).
<br><br>

<?gtt $memo $billable $billrate $task_time $value $bill_value 
$start_datime $stop_datime $elapsed $table ?>

<!--
<?gtt $memo $billable $billrate $value $bill_value $table ?>
-->

<br><br>
That's all Folks!
</body>
</html>
