/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Start Fuzz");
gchar *s = N_("Stop");
gchar *s = N_("Start");
gchar *s = N_("Set how Uncertain the Start Time Is");
gchar *s = N_("Exact Time");
gchar *s = N_("5 Min");
gchar *s = N_("10 Min");
gchar *s = N_("15 Min");
gchar *s = N_("20 Min");
gchar *s = N_("30 Min");
gchar *s = N_("1 Hour");
gchar *s = N_("2 Hours");
gchar *s = N_("3 Hours");
gchar *s = N_("Today");
