/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Edit the Start & Stop Times");
gchar *s = N_("Edit");
gchar *s = N_("Delete This Interval");
gchar *s = N_("Delete");
gchar *s = N_("Merge Into Interval Above");
gchar *s = N_("Merge Up");
gchar *s = N_("Merege Into Interval Below");
gchar *s = N_("Merge Down");
