/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Journal");
gchar *s = N_("New File");
gchar *s = N_("Print");
gchar *s = N_("Open File");
gchar *s = N_("Save");
gchar *s = N_("Save File");
gchar *s = N_("Close");
