/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("A title to assign to this project");
gchar *s = N_("a short description that will be printed on the invoice.");
gchar *s = N_("Project Title:");
gchar *s = N_("Project Description:");
gchar *s = N_("Notes:");
gchar *s = N_("Internal notes about the project, memos that will not be printed on an invoice.");
gchar *s = N_("Project");
gchar *s = N_("Regular Rate:");
gchar *s = N_("Overtime Rate:");
gchar *s = N_("Double-Overtime Rate:");
gchar *s = N_("Flat Fee:");
gchar *s = N_("        ");
gchar *s = N_("                        ");
gchar *s = N_("The dollars per hour normally charged for this project.");
gchar *s = N_("The dollars per hour charged for overtime work on this project.");
gchar *s = N_("The over-overtime rate (overtime on Sundays, etc.)");
gchar *s = N_("If this project is billed for one price no matter how long it takes, enter the fee here.");
gchar *s = N_("Rates");
gchar *s = N_("Minimum Interval: ");
gchar *s = N_("Auto-merge Interval:");
gchar *s = N_("Auto-merge Gap:");
gchar *s = N_("seconds");
gchar *s = N_("seconds");
gchar *s = N_("seconds");
gchar *s = N_("Intervals smaller than this will be discarded");
gchar *s = N_("Time below which an interval is merged with its neighbors");
gchar *s = N_("If the gap between intervals is smaller than this, the intervals will be merged together.");
gchar *s = N_("Intervals");
