/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Project Title:");
gchar *s = N_("Project Description:");
gchar *s = N_("Notes:");
gchar *s = N_("Project");
gchar *s = N_("Regular Rate:");
gchar *s = N_("Overtime Rate:");
gchar *s = N_("Double-Overtime Rate:");
gchar *s = N_("Flat Fee:");
gchar *s = N_("        ");
gchar *s = N_("                        ");
gchar *s = N_("Rates");
gchar *s = N_("Minimum Interval: ");
gchar *s = N_("Auto-merge Interval:");
gchar *s = N_("Auto-merge Gap:");
gchar *s = N_("seconds");
gchar *s = N_("Time below which intervals are discarded");
gchar *s = N_("Time below which an interval is merged with its neighbors");
gchar *s = N_("If the gap between intervals is smaller than tis, the intervals will be merged together");
gchar *s = N_("seconds");
gchar *s = N_("seconds");
gchar *s = N_("Intervals");
