/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Memo:");
gchar *s = N_("Notes:");
gchar *s = N_("Billable:");
gchar *s = N_("Billing Rate:");
gchar *s = N_("Billing Block:");
gchar *s = N_("Can this task be billed to the customer?  \"Hold\" means maybe but not yet, \"Not Billable\" means don't print on the invoice, \"No Charge\" means print on the invoice as 'free'.");
gchar *s = N_("Hold");
gchar *s = N_("Billable");
gchar *s = N_("Not Billable");
gchar *s = N_("No Charge");
gchar *s = N_("Fee rate to be charged for this task.");
gchar *s = N_("Regular");
gchar *s = N_("Overtime");
gchar *s = N_("OverOver");
gchar *s = N_("Flat Fee");
gchar *s = N_("The billed unit of time wioll be rounded to an integer multiple of this time.");
gchar *s = N_("A set of private notes that will not be printed on an invoice.");
gchar *s = N_("A short description to attach to this block of time.");
gchar *s = N_("minutes");
gchar *s = N_("Task Properties");
