/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Memo:");
gchar *s = N_("Notes:");
gchar *s = N_("Billable:");
gchar *s = N_("Billing Rate:");
gchar *s = N_("Billing Unit:");
gchar *s = N_("Hold");
gchar *s = N_("Billable");
gchar *s = N_("Not Billable");
gchar *s = N_("No Charge");
gchar *s = N_("Regular");
gchar *s = N_("Overtime");
gchar *s = N_("OverOver");
gchar *s = N_("Flat Fee");
