"Alan Cox",
"Bertrand Guiheneuf",
"Christopher Blizzard",
"Daniel Veillard",
"Eckehard Berns",
"Elliot Lee",
"Eskil Heyn Olsen",
"Ettore Perazzoli",
"Federico Mena",
"Frederic Devernay",
"George Lebl",
"Gregory McLean",
"Havoc Pennington",
"Heath Martin Seth Alves",
"Jaka Mocnik",
"James Henstridge",
"James Youngman",
"Jens Ch. Restemeier",
"Jens Christian Restemeier",
"John Ellis",
"Jonathan",
"Jonathan Blandford",
"Justin Maurer",
"Manish Vachharajani",
"Marc Ewing",
"Marius Vollmer",
"Michael Fulbright",
"Michael Hanni",
"Michael K. Johnson",
"Miguel de Icaza",
"Molaro Paolo",
"Neil Vachharajani",
"Owen Taylor",
"Paul Sheer",
"Radek Doulik",
"Raph Levien",
"Robert Richardson",
"Shawn Amundson",
"Szekeres Istvan",
"The Rasterman",
"Tim Janik",
"Tim P. Gerla",
"Timur Bakeyev",
"Tom Tromey",
"Tuomas Kuosmanen",
