"Eckehard Berns",
"Elliot Lee",
"Federico Mena",
"George Lebl",
"Jaka Mocnik",
"Jens Christian Restemeier",
"Manish Vachharajani",
"Marius Vollmer",
"Maurer Dietmar",
"Michael Fulbright",
"Michael K. Johnson",
"Miguel de Icaza",
"Molaro Paolo",
"Neil Vachharajani",
"Owen Taylor",
"Radek Doulik",
"Seth Alves",
"Szekeres Istvan",
"Tim Janik",
"Tom Tromey",
"Tuomas Kuosmanen",
