.\" gnome-search-tool.1 - GNOME Search Tool
.\" Copyright 2001  Jochen Voss
.TH gnome-search-tool 1 "Aug 09 2002" "gnome-utils 2.0.0"
.SH NAME
gnome-search-tool \- the GNOME Search Tool
.SH SYNOPSIS
.B gnome-search-tool
.sp
or select
.B Search for Files...
from the GNOME menu or from the 
.B Actions 
menu in the Menu Panel.
.SH DESCRIPTION
.B GNOME Search Tool
is a utility for searching files on your system. It can perform many
types of search: by filename, by modification date, by file contents,
etc.

For full documentation see the
.B GNOME Search Tool
online help.

.SH AUTHOR
.B GNOME Search Tool
was written by George Lebl (<jirka@5z.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR find (1)
.BR locate (1)
