.TH gtt 1 "11 Feb 1998" "GNOME" "The GNOME Project"
.SH NAME
gtt - GTimeTracker - a time tracker
.SH SYNOPSIS
.B gtt
.RB [ --display
.IR displayname ]
.RB [ -geometry
.IR geometry ]
.SH DESCRIPTION
.PP
.I GTimeTracker
is just a tool to measure the time, you let a given project in a selected
state.
.I GTimeTracker
isn't espacially smart at this. You, the user, will have to give
GTimeTracker hints about what you're currently wanting to measure or it will
not display reasonable values.
.PP
But when one has learned to use
.I GTimeTracker
effectively, it can be of great help. For example you can use it to optimize
your work. It can show you, that you are spending to much time on
unimportent tasks. Or it can exactly count the hours you spend on a project,
that is payed for by time. You may discover many other ways,
.I GTimeTracker
can work for you.
.SH OPTIONS
.TP
.B --display
specifies the X server, gtt should connect to. Refer to the X(1x) manual
page for more info.
.TP
.B -geometry
specifies the
.I geometry
of the main window. The syntax is
.B [WIDTHxHEIGHT][(+|-)X(+|-)Y]
just like the X toolkit option
.I geometry. See X(1x) for more info.
.SH OTHER TYPES OF DOCUMENTATION
You can find more information about
.I GTimeTracker
and its functions in the
.I Gnome help system.
Just select
.B Contents
from the 
.B Help
menu to get there.
.SH "SEE ALSO"
X(1x)
.SH THANKS
.PP
Thanks to Olivier Fontenelle and Tuomas Kuosmanen for ideas and bug reports.
Thanks to Tom Tromey for his style corrections to GTT. And thanks to Miguel
de Icaza for discussing some GNOME features with me, as well as including
GTT in the GNOME CVS tree.
.SH AUTHOR
Copyright (C) 1997,98 Eckehard Berns
.\"   This program is free software; you can redistribute it and/or modify
.\"   it under the terms of the GNU General Public License as published by
.\"   the Free Software Foundation; either version 2 of the License, or
.\"   (at your option) any later version.
.\"
.\"   This program is distributed in the hope that it will be useful,
.\"   but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"   GNU General Public License for more details.
.\"
.\"   You should have received a copy of the GNU General Public License
.\"   along with this program; if not, write to the Free Software
.\"   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.\"   For more details see the file COPYING.
