.\" gnome-character-map.1 - GNOME Character Map
.\" Copyright 2001  Jochen Voss
.TH gnome-character-map 1 "Aug 8 2002" "gnome-utils 2.0.0"
.SH NAME
gnome-character-map \- the GNOME Character Map
.SH SYNOPSIS
.B gnome-character-map
.sp
or select
.B Character Map
from the
.B Accessories
submenu of the Applications menu.
.SH DESCRIPTION
.B GNOME Character Map
is a program that allows you to select any character available in your
current font.  With
.BR "GNOME Character Map" ,
you can also use characters that you cannot type with your keybord
(such as "extended ASCII characters", or characters with codes greater
than 127, for example the copyright symbol).

For full documentation see the
.B GNOME Character Map
online help.

.SH AUTHOR
.B GNOME Character Map
was written by Hongli Lai (<h.lai@chello.nl>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.
