module gnome_PIM {
  
  /* Exceptions */
  exception PIM_busy{
  };
  
  /* Types */
  struct vCard {
  
    string ID;
  };
  typedef sequence<vCard> vCard_seq;
  
  interface vCard_server {
     vCard_seq get_records ();
    
     vCard get_record (in string ID);
     void set_record (in string ID, vCard record);
  }
}
  
