.\" archive-generator.1 - a graphical frontend for tar
.\" Copyright 2001  Jochen Voss
.TH archive-generator 1 "Jun 26 2001" "gnome-utils 1.4.0.1"
.SH NAME
archive-generator \- a graphical front end for tar
.SH SYNOPSIS
.B archive-generator
.sp
or select
.B Archive Generator
from the
.B Utilities
submenu of the Main Menu.
.SH DESCRIPTION
.B archive-generator
is a graphical front end for the tar unix utility.
You can use drag and drop to assemble files and directories
in the
.B archive-generator
window.  When finished you press a button to pack all the stuff
into a single tar archive.  Very handy!
.P
For full documentation see the
.B archive-generator
online help.
.SH AUTHOR
.B archive-generator
was written by George Lebl (<jirka@5z.com>).
.P
This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.
.SH SEE ALSO
.BR tar (1)
