.\" gnome-calculator.1 - GNOME Calculator
.\" Copyright 2001  Jochen Voss
.TH gnome-calculator 1 "Aug 08 2002" "gnome-utils 2.0.0"
.SH NAME
gnome-calculator \- GNOME Calculator
.SH SYNOPSIS
.B gnome-calculator
.sp
or select
.B Calculator
from the
.B Accessories
submenu of the Applications menu.
.SH DESCRIPTION
.B GNOME Calculator
is a double precision calculator application.  It provides advanced
scientific and mathematical features such as trigonometric functions
(sine, cosine, tangent) and logarithms (log, ln).

For full documentation see the
.B GNOME Calculator
online help.

.SH AUTHOR
.B GNOME Calculator
was written by George Lebl (<jirka@5z.com>).

This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR xcalc (1x),
.BR dc (1)
